include src/about/Makefile.inc
include src/blog/Makefile.inc
include src/css/Makefile.inc
include src/fonts/Makefile.inc
include src/icons/Makefile.inc
include src/lib/Makefile.inc
include src/manifest/Makefile.inc
include src/projects/Makefile.inc

FILES += \
	src/dream-data-code.webp \
	src/spa.html \
	src/robots.txt \
	src/sitemap.xml

TS_FILES += src/app.ts
